name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pyinstaller
        pip install PySimpleGUI-4-foss
        pip install pyyaml
        pip install pysam

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed main.py --hidden-import yaml --add-data "scripts/bio/motifs_data.yaml;scripts/bio" --add-data "scripts/bio/clinical_thresholds.yaml;scripts/bio"

    - name: Show dist folder
      run: |
        echo "Listing dist folder:"
        dir dist

    # --------------------------------------------------------------------
    # MODE NORMAL : upload de l'exécutable en artifact.
    # À réactiver dès que GitHub libère le quota.
    # --------------------------------------------------------------------
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: trgt-parser-exe
        path: dist/main.exe
        compression-level: 0

