name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pyinstaller
        pip install PySimpleGUI-4-foss
        pip install pyyaml

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed main.py --hidden-import yaml --add-data "scripts/bio/motifs_data.yaml;scripts/bio" --add-data "scripts/bio/clinical_thresholds.yaml;scripts/bio"

    - name: Show dist folder
      run: |
        echo "Listing dist folder:"
        dir dist

    # --------------------------------------------------------------------
    # MODE SECOURS : extraction de l'exécutable quand le quota artifact
    # est plein et que GitHub refuse l'upload.
    #
    # Cette étape encode l'exe en hex pour pouvoir le récupérer dans les logs.
    # À utiliser uniquement quand les artifacts sont bloqués.
    # Génère un ZIP contenant main.hex et l'affiche en base64
    # pour pouvoir le récupérer facilement sans artifacts.
    # --------------------------------------------------------------------
    - name: Encode EXE in hex and package as ZIP (EMERGENCY ONLY)
      run: |
        certutil -encodehex dist/main.exe main.hex
        powershell Compress-Archive -Path main.hex -DestinationPath main_hex.zip
        certutil -encode main_hex.zip main_hex.b64
        type main_hex.b64


    # --------------------------------------------------------------------
    # MODE NORMAL : upload de l'exécutable en artifact.
    # À réactiver dès que GitHub libère le quota.
    # --------------------------------------------------------------------
    # - name: Upload EXE artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: trgt-parser-exe
    #     path: dist/main.exe
    #     compression-level: 0
